---
- name: Deploy Global Hub Observability Alerts Policy
  kubernetes.core.k8s:
    kubeconfig: "{{ target_kubeconfig }}"
    state: present
    template: alerts-policy.yaml.j2

- name: Deploy Placement and Binding for Global Hub
  kubernetes.core.k8s:
    kubeconfig: "{{ target_kubeconfig }}"
    state: present
    template: alerts-placement.yaml.j2
