---
- name: Configure Managed Cluster Add-on Strategies (On Regional Hub)
  kubernetes.core.k8s:
    kubeconfig: "{{ target_kubeconfig }}"
    state: present
    template: "managed-clusters-strategy.yaml.j2"
  loop:
    - governance-policy-framework
    - config-policy-controller
    - search-collector