---
- name: Install OCP on AWS
  gather_facts: false
  hosts: localhost
  tasks:
    - debug:
        msg: "Provisioning and Configuring Full Global Hub Environment on AWS"

- name: Create Global Hub
  ansible.builtin.import_playbook: create-global-hub.yaml

- name: Create Regional Hub
  ansible.builtin.import_playbook: create-managed-hub.yaml

- name: Create Managed Cluster
  ansible.builtin.import_playbook: create-managed-cluster.yaml
...